openapi: 3.0.0
info:
  title: "Translation API"
  version: "1.0.0"

paths:
  /translations:
    get:
      summary: "Get all translations"
      responses:
        "200":
          description: "Success"
